name: publish docker image

on:
  push:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: pgirich/rmji:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

      - name: Login to GitHub Container Registry
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.FULL_TOKEN }}

      - name: Push the Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}
