name: publish docker image

on:
  push:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: pgirich/rmji:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to GitHub Container Registry
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.FULL_TOKEN }}

      - name: Push the Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Deploy to VPS
        uses: invi5H/ssh-action@v1
        with:
          NAME: bar
          SSH_HOST: ${{ secrets.VPS_IP }}
          SSH_PORT: 22
          SSH_USER: ${{ secrets.VPS_LOGIN }}
          SSH_KEY: ${{ secrets.VPS_KEY }}

      - name: Deploy to VPS by SSH
        run: ssh ${{ secrets.VPS_LOGIN }}@${{ secrets.VPS_IP }} -v -i /home/runner/.ssh/id_rsa "docker compose pull && docker compose up -d && exit"

      - name: Deploy to VPS
        uses: nekiro/ssh-job@main
        with:
          host: ${{ secrets.VPS_IP }}
          key: ${{ secrets.VPS_KEY }}
          user: ${{ secrets.VPS_LOGIN }}
          password: ${{ secrets.VPS_PASSWORD }}
          command: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{  secrets.FULL_TOKEN }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_LOGIN }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.FULL_TOKEN }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_KEY }}
          known_hosts: ${{ secrets.VPS_IP }}
