name: publish docker image

on:
  push:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  REGISTRY_USER: PGirich
  IMAGE_NAME: pgirich/rmji:latest
  SSH: ssh ${{ secrets.VPS_LOGIN }}@${{ secrets.VPS_IP }} -i ~/.ssh/id_rsa

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - name: ${{ github.actor }} run checkout for ${{ github.repository}}
        uses: actions/checkout@v4

      - name: Build the Docker image - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to GitHub Container Registry - ${{ env.REGISTRY }}
        run: |
          docker login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USER }} -p ${{ secrets.GHCR_PAT }}

      - name: Push the Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Install SSH key of VPS
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} > ~/.ssh/known_hosts

      - name: Login to registry - ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}
        run: |
          ${{ env.SSH }} "docker login ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }} -u ${{ env.REGISTRY_USER }} -p ${{ secrets.GHCR_PAT }}"

      - name: Deploy to VPS by SSH - pull
        run: |
          ${{ env.SSH }} "sudo docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Deploy to VPS by SSH - run
        run: |
            ${{ env.SSH }} "sudo docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
