name: publish docker image

on:
  push:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  REGISTRY_USER: PGirich
  IMAGE_NAME: pgirich/rmji:latest
  SSH: ssh ${{ secrets.VPS_LOGIN }}@${{ secrets.VPS_IP }} -i ~/.ssh/id_rsa

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - name: ${{ github.actor }} run checkout for ${{ github.repository}}
        uses: actions/checkout@v4

      - name: Build the Docker image - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to GitHub Container Registry - ${{ env.REGISTRY }}
        run: |
          docker login ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }} -u ${{ env.REGISTRY_USER }} -p ${{ secrets.GHCR_PAT }}

      - name: Push the Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Install SSH key of VPS
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} > ~/.ssh/known_hosts

      - name: Login to registry - ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}
        run: |
          ${{ env.SSH }} "sudo docker login ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }} -u ${{ env.REGISTRY_USER }} -p ${{ secrets.GHCR_PAT }}"

      - name: Deploy certbot to VPS by SSH - volume
        run: |
          ${{ env.SSH }} "sudo mkdir -p -v /etc/nginx/user_conf.d/"
          ${{ env.SSH }} "sudo touch /etc/nginx/user_conf.d/nginx.conf"
          ${{ env.SSH }} "sudo chmod 777 /etc/nginx/user_conf.d/nginx.conf"
          ${{ env.SSH }} "sudo echo "server { \
              listen 443 ssl default_server reuseport; \
              listen [::]:443 ssl default_server reuseport; \
              server_name rmji.ru www.rmji.ru; \
              ssl_certificate /etc/letsencrypt/live/rmji/fullchain.pem; \
              ssl_certificate_key /etc/letsencrypt/live/rmji/privkey.pem; \
              ssl_trusted_certificate /etc/letsencrypt/live/rmji/chain.pem; \
              ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem; \
              return 200 'Let\'s Encrypt certificate successfully installed!'; \
              add_header Content-Type text/plain; \
            }" >> /etc/nginx/user_conf.d/nginx.conf"

      - name: Deploy certbot to VPS by SSH - pull
        run: |
          ${{ env.SSH }} "sudo docker pull jonasal/nginx-certbot:latest"

      - name: Deploy certbot to VPS by SSH - create
        run: |
          ${{ env.SSH }} "sudo docker create -it -p 80:80 -p 443:443 \
           --env CERTBOT_EMAIL=petr.girich@yandex.ru \
           -v /etc/nginx/nginx_secrets:/etc/letsencrypt \
           -v /etc/nginx/user_conf.d:/etc/nginx/user_conf.d:ro \
           --name certbot --pull never \
           jonasal/nginx-certbot"

      - name: Deploy app to VPS by SSH - pull
        run: |
          ${{ env.SSH }} "sudo docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Deploy to VPS by SSH - run
        run: |
          ${{ env.SSH }} "sudo docker run --name rmji ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
