name: publish docker image

on:
  push:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  REGISTRY_USER: PGirich
  IMAGE_NAME: pgirich/rmji:latest
  SSH: ssh ${{ secrets.VPS_LOGIN }}@${{ secrets.VPS_IP }} -i ~/.ssh/id_rsa
  CERT_PATH: /etc/nginx/nginx_secrets/live/rmji
  DHP_PATH: /etc/nginx/nginx_secrets/dhparams
  CONF_PATH: /etc/nginx/user_conf.d

jobs:
  certbot:
    name: publish certbot
    runs-on: ubuntu-latest

    steps:
      - name: ${{ github.actor }} run checkout for ${{ github.repository}}
        uses: actions/checkout@v4

      - name: Install SSH key of VPS
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} > ~/.ssh/known_hosts

      - name: Install certbot artefacts
        run: |
           ${{ env.SSH }} "sudo mkdir -p -v ${{ env.CERT_PATH }} || exit 0"

      - name: Kill containers on VPS
        run: |
          ${{ env.SSH }} "sudo docker rm -f certbot || exit 0"

      - name: Login to registry from VPS - ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}
        run: |
          ${{ env.SSH }} "sudo docker login ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }} -u ${{ env.REGISTRY_USER }} -p ${{ secrets.GHCR_PAT }}"

      - name: Pull certbot to VPS
        run: |
          ${{ env.SSH }} "sudo docker pull certbot/certbot:latest"

      - name: Create certbot container on VPS
        run: |
          ${{ env.SSH }} "sudo docker create \
            -it -p 80:80 \
            -v /etc/nginx/nginx_secrets:/etc/letsencrypt \
            --name certbot --pull never \
            certbot/certbot \
            certonly --standalone --non-interactive \
            --email petr.girich@yandex.ru \
            --agree-tos \
            --preferred-challenges http \
            --dry-run \
            -d rmji.ru -d www.rmji.ru \
            "

      - name: Create certbot container on VPS
        run: |
          ${{ env.SSH }} "sudo docker container start -a certbot"

  publish:
    name: publish rmji.ru app
    runs-on: ubuntu-latest
    needs: certbot

    steps:
      - name: Error
        run: |
          exit -1

      - name: ${{ github.actor }} run checkout for ${{ github.repository}}
        uses: actions/checkout@v4

      - name: Install SSH key of VPS
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} > ~/.ssh/known_hosts

      - name: Build the Docker image - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to GitHub Container Registry - ${{ env.REGISTRY }}
        run: |
          docker login ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }} -u ${{ env.REGISTRY_USER }} -p ${{ secrets.GHCR_PAT }}

      - name: Push the Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Kill containers on VPS
        run: |
          ${{ env.SSH }} "sudo docker rm -f rmji || exit 0"

      - name: Login to registry from VPS - ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}
        run: |
          ${{ env.SSH }} "sudo docker login ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }} -u ${{ env.REGISTRY_USER }} -p ${{ secrets.GHCR_PAT }}"

      - name: Pull app to VPS
        run: |
          ${{ env.SSH }} "sudo docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Run app image on VPS
        run: |
          ${{ env.SSH }} "sudo docker run --name rmji ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
